version: "3"

services:
  mongo:
    image: "mongo:4.0.24-xenial"
  
  backend:
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    image: backend
    build: backend
    ports:
      - "8000:8000"
